/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MorningLightLotsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COOLDOWN_SECONDS"
      | "DAILY_LIMIT"
      | "FORTUNE_COUNT"
      | "SECONDS_PER_DAY"
      | "canDrawNow"
      | "confidentialProtocolId"
      | "drawFortune"
      | "getLastDrawTimestamp"
      | "getMyFortune"
      | "getMyFortuneCount"
      | "getRemainingCooldown"
      | "getTodayDrawCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FortuneDrawn"): EventFragment;

  encodeFunctionData(
    functionFragment: "COOLDOWN_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAILY_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FORTUNE_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_DAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canDrawNow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "drawFortune",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastDrawTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyFortune",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyFortuneCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTodayDrawCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COOLDOWN_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAILY_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FORTUNE_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_DAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canDrawNow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawFortune",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastDrawTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyFortune",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyFortuneCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTodayDrawCount",
    data: BytesLike
  ): Result;
}

export namespace FortuneDrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    drawId: BigNumberish,
    timestamp: BigNumberish,
    dayIndex: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    drawId: bigint,
    timestamp: bigint,
    dayIndex: bigint
  ];
  export interface OutputObject {
    user: string;
    drawId: bigint;
    timestamp: bigint;
    dayIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MorningLightLots extends BaseContract {
  connect(runner?: ContractRunner | null): MorningLightLots;
  waitForDeployment(): Promise<this>;

  interface: MorningLightLotsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COOLDOWN_SECONDS: TypedContractMethod<[], [bigint], "view">;

  DAILY_LIMIT: TypedContractMethod<[], [bigint], "view">;

  FORTUNE_COUNT: TypedContractMethod<[], [bigint], "view">;

  SECONDS_PER_DAY: TypedContractMethod<[], [bigint], "view">;

  canDrawNow: TypedContractMethod<[], [boolean], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  drawFortune: TypedContractMethod<[], [void], "nonpayable">;

  getLastDrawTimestamp: TypedContractMethod<[], [bigint], "view">;

  getMyFortune: TypedContractMethod<
    [fortuneIndex: BigNumberish],
    [string],
    "nonpayable"
  >;

  getMyFortuneCount: TypedContractMethod<[], [bigint], "view">;

  getRemainingCooldown: TypedContractMethod<[], [bigint], "view">;

  getTodayDrawCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COOLDOWN_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAILY_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FORTUNE_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canDrawNow"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "drawFortune"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLastDrawTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyFortune"
  ): TypedContractMethod<[fortuneIndex: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getMyFortuneCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemainingCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTodayDrawCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FortuneDrawn"
  ): TypedContractEvent<
    FortuneDrawnEvent.InputTuple,
    FortuneDrawnEvent.OutputTuple,
    FortuneDrawnEvent.OutputObject
  >;

  filters: {
    "FortuneDrawn(address,uint256,uint256,uint256)": TypedContractEvent<
      FortuneDrawnEvent.InputTuple,
      FortuneDrawnEvent.OutputTuple,
      FortuneDrawnEvent.OutputObject
    >;
    FortuneDrawn: TypedContractEvent<
      FortuneDrawnEvent.InputTuple,
      FortuneDrawnEvent.OutputTuple,
      FortuneDrawnEvent.OutputObject
    >;
  };
}
